# Generated by Django 5.1.4 on 2025-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4'), ('pdf', 'PDF'), ('other', 'Другое')], max_length=20, verbose_name='Формат'),
        ),
    ]
