# Generated by Django 5.1.4 on 2025-01-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Хэш изображения'),
        ),
    ]
