# Generated by Django 5.1.4 on 2025-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_content_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_hash',
            field=models.TextField(blank=True, null=True, verbose_name='Хэш изображения'),
        ),
    ]
